[package]
name = "root"
version = "0.1.0"
authors = ["app"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0"
actix-web = "2.0"
envy = "0.3.3"
deadpool-postgres = "0.5.0"
failure = "0.1.6"
serde = "1.0.104"
serde_derive = "1.0.104"
tokio-postgres = "0.5.1"

[profile.release]
panic = "abort"
